cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ViewCart.as_view(), name='view_cart'),
    path('add/<item_id>/', views.AddToCart.as_view(), name='add_to_cart'),
    path('edit/<item_id>/', views.EditCart.as_view(), name='edit_cart'),
    path('delete/<item_id>/', views.DeleteFromCart.as_view(
        ), name='delete_from_cart'),
]

gamers_ground/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

rating_choices = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class Review(models.Model):
    """Main model for leaving reviews & ratings on products"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE)
    rating = models.IntegerField(choices=rating_choices, default=5)
    review = models.TextField(max_length=500, null=False, blank=False)
    created_on = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f'{self.user} reviewed {self.product} | Rating: {self.rating}'

cart/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from django.views import generic
from products.models import Product


class ViewCart(generic.TemplateView):
    """Renders the cart page with saved items"""
    template_name = 'cart/cart.html'


class AddToCart(generic.View):
    """
    Adds product to cart. If it already exists in cart,
    increments qty by one.
    """
    def post(self, request, item_id):

        item = get_object_or_404(Product, pk=item_id)
        redirect_url = request.POST.get('redirect_url')
        cart = request.session.get('cart', {})

        if item_id in list(cart.keys()):
            cart[item_id] += 1
            messages.success(
                request, f'Updated {item.name} quantity to \
                {cart[item_id]} in your cart!', extra_tags='show-cart')
        else:
            cart[item_id] = 1
            messages.success(
                request, f'Added {item.name} to your cart!',
                extra_tags='show-cart')

        request.session['cart'] = cart
        return redirect(redirect_url)


class EditCart(generic.View):
    """
    Sets product qty to user input in cart.
    If input is 0, removes from cart.
    """
    def post(self, request, item_id):

        item = get_object_or_404(Product, pk=item_id)
        quantity = int(request.POST.get('quantity'))
        cart = request.session.get('cart', {})

        if quantity > 0:
            cart[item_id] = quantity
            messages.success(
                request, f'Updated {item.name} quantity to \
                {cart[item_id]} in your cart!', extra_tags='show-cart')
        else:
            del cart[item_id]
            messages.success(
                request, f'Removed {item.name} from your cart!',
                extra_tags='show-cart')

        request.session['cart'] = cart
        return redirect('view_cart')


class DeleteFromCart(generic.View):
    """
    Delete product from cart.
    If product not found in cart, display error message.
    """
    def get(self, request, item_id):

        try:
            item = get_object_or_404(Product, pk=item_id)
            cart = request.session.get('cart', {})

            del cart[item_id]
            messages.success(
                request, f'Removed {item.name} from your cart!',
                extra_tags='show-cart')

            request.session['cart'] = cart
            return redirect('view_cart')
        except Exception as e:
            messages.error(
                request, f'Error removing item: {e}', extra_tags='show-cart')
            return redirect('view_cart')

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <div class="row mt-4">
                <div class="col-10 offset-1">
                    <p>
                        <a class="text-link" href="{% url 'products' %}"><i class="fa-solid fa-arrow-left"></i> Continue shopping</a>
                    </p>
                </div>
            </div>
            <div class="row text-uppercase text-center mt-3">
                <div class="col">
                    <h2>Shopping cart</h2>
                </div>
            </div>
            <div class="row">
                <div class="cart-container col-10 offset-1">
                    {% if cart_items %}
                        <!-- Delivery info -->
                        <div class="row my-3">
                            <div class="col">
                                {% if free_delivery_delta == 0 %}
                                    <p class="text-center"><i class="fa-solid fa-truck"></i> You have qualified for free delivery!</p>
                                {% else %}
                                    <p class="text-center"><i class="fa-solid fa-truck"></i> Spend ${{ free_delivery_delta }} more to get free delivery!</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <!-- Order information -->
                            <div class="col-12 col-md-4 order-md-last my-5 px-0 ps-md-3">
                                <h5 class="text-center mb-5">Order Info ({{ product_count }} items)</h5>
                                <div class="row">
                                    <div class="col-6">
                                        Cart Total:
                                    </div>
                                    <div class="col-6 text-end">
                                        ${{ total }}
                                    </div>
                                </div>
                                <div class="row my-2">
                                    <div class="col-6">
                                        Delivery:
                                    </div>
                                    <div class="col-6 text-end">
                                        {% if free_delivery_delta == 0 %}
                                            <del>${{ standard_delivery }}</del> <span class="ms-1">${{ delivery }}</span>
                                        {% else %}
                                            ${{ delivery }}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row fw-6">
                                    <div class="col-7">
                                        Grand Total:
                                    </div>
                                    <div class="col-5 text-end">
                                        ${{ grand_total }}
                                    </div>
                                </div>
                                <a class="btn btn-green text-uppercase float-end mt-5" href="{% url 'checkout' %}"><i class="fa-solid fa-lock"></i> Secure checkout</a>
                            </div>
                            <!-- Loop over each product in cart -->
                            <div class="col-12 col-md-8">
                                {% for item in cart_items %}
                                    <div class="row bg-grey rounded border-black my-5">
                                        <div class="col-12 col-sm-6">
                                            {% if item.product.image %}
                                                <a href="{% url 'product_detail' item.product.category.slug item.product.slug %}">
                                                    <img class="cart-img w-100 fit-scale py-3" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
                                                </a>
                                            {% else %}
                                                <a href="{% url 'product_detail' item.product.category.slug item.product.slug %}">
                                                    <img class="cart-img w-100 fit-scale py-3" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
                                                </a>
                                            {% endif %}
                                        </div>
                                        <div class="col-12 col-sm-6 my-3 pe-sm-4 d-flex flex-column">
                                            <div class="row">
                                                <div class="col-6">
                                                    {% if item.product.brand %}
                                                        <p class="text-muted mb-0">{{ item.product.brand }}</p>
                                                    {% endif %}
                                                </div>
                                                <div class="col-6 text-end">
                                                    <a class="text-white" href="{% url 'delete_from_cart' item.item_id %}" aria-label="Delete from cart">
                                                        <i class="fa-solid fa-trash-can"></i>
                                                    </a>
                                                </div>
                                            </div>
                                            <a class="text-link" href="{% url 'product_detail' item.product.category.slug item.product.slug %}">
                                                <h4>{{ item.product.name }}</h4>
                                            </a>
                                            {% if item.product.avg_rating %}
                                                <div class="mb-3">
                                                    <span class="product-star-rating">
                                                        <i class="fa-solid fa-star{% if product.avg_rating < 0.5 %}-o{% elif product.avg_rating >= 0.5 and product.avg_rating < 1 %}-half{% endif %}" aria-hidden="true"></i>
                                                        <i class="fa-solid fa-star{% if product.avg_rating < 1.5 %}-o{% elif product.avg_rating >= 1.5 and product.avg_rating < 2 %}-half{% endif %}" aria-hidden="true"></i>
                                                        <i class="fa-solid fa-star{% if product.avg_rating < 2.5 %}-o{% elif product.avg_rating >= 2.5 and product.avg_rating < 3 %}-half{% endif %}" aria-hidden="true"></i>
                                                        <i class="fa-solid fa-star{% if product.avg_rating < 3.5 %}-o{% elif product.avg_rating >= 3.5 and product.avg_rating < 4 %}-half{% endif %}" aria-hidden="true"></i>
                                                        <i class="fa-solid fa-star{% if product.avg_rating < 4.5 %}-o{% elif product.avg_rating >= 4.5 and product.avg_rating < 5 %}-half{% endif %}" aria-hidden="true"></i>
                                                        <small>({{ item.product.review_set.all.count }})</small>
                                                    </span>
                                                </div>
                                            {% else %}
                                                <p><small class="text-muted">No Rating</small></p>
                                            {% endif %}
                                            <!-- order item info -->
                                            <div class="row mt-auto">
                                                <div class="col-6">
                                                    Price:
                                                </div>
                                                <div class="col-6 text-end">
                                                    ${{ item.product.price }}
                                                </div>
                                            </div>
                                            <div class="row my-2">
                                                <div class="col-6">
                                                    Quantity:
                                                </div>
                                                <div class="col-6 text-end">
                                                    <!-- Form for updating item quantity -->
                                                    <form id="update-qty-form-{{ item.item_id }}" method="POST" action="{% url 'edit_cart' item.item_id %}">
                                                        {% csrf_token %}
                                                        <div class="input-group justify-content-end">
                                                            <div class="input-group-prepend">
                                                                <button class="btn btn-sm decrement-qty btn-green" id="decrement-qty_{{ item.item_id }}"
                                                                    data-item_id="{{ item.item_id }}" aria-label="Decrement item quantity">
                                                                    <i class="fa-solid fa-minus"></i>
                                                                </button>
                                                            </div>
                                                            <input class="form-control qty-input" type="number" name="quantity" value="{{ item.quantity }}"
                                                                min="1" max="99" data-item_id="{{ item.item_id }}" id="id_qty_{{ item.item_id }}" aria-label="Item quantity input">
                                                            <div class="input-group-append">
                                                                <button class="btn btn-sm increment-qty btn-green" id="increment-qty_{{ item.item_id }}"
                                                                    data-item_id="{{ item.item_id }}" aria-label="Increment item quantity">
                                                                    <i class="fa-solid fa-plus"></i>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="row fw-6">
                                                <div class="col-6">
                                                    Total:
                                                </div>
                                                <div class="col-6 text-end">
                                                    ${{ item.item_total }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% else %}
                        <p class="text-center mt-5">Your cart is currently empty.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Back to top button -->
        <div>
            <span class="btt-link btn btn-green">
                <i class="fa-solid fa-arrow-up mt-2"></i>
            </span>
        </div>
    </main>

    <script>
        document.querySelector('.btt-link').onclick = function() {
            window.scrollTo(0,0);
        };
    </script>

    <script src="{% static 'js/itemQuantityInput.js' %}"></script>
{% endblock %}